name: Seven Days Yoga
description: Website for Seven Days Yoga Studio.
url: sevendaysyoga.com
permalink: :categories/:title
exclude: [vendor]
markdown: kramdown
redcarpet:
 extensions: ['tables', 'smart', 'with_toc_data', 'superscript']
gems:
  - jekyll-sitemap
